### ISSUE TITLE
I get multiple error when running the test program.

### ISSUE THREAD

**Issue by hairem** [adafruit/Adafruit_CircuitPython_MCP4725#15]
pi@raspberrypi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- 62 -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
pi@raspberrypi:~ $ sudo python3 DAC.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 172, in __probe_for_device
    self.i2c.writeto(self.device_address, b"")
  File "/usr/local/lib/python3.7/dist-packages/busio.py", line 116, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 49, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO/smbus.py", line 308, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 178, in __probe_for_device
    self.i2c.readfrom_into(self.device_address, result)
  File "/usr/local/lib/python3.7/dist-packages/busio.py", line 106, in readfrom_into
    return self._i2c.readfrom_into(address, buffer, stop=stop)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 56, in readfrom_into
    readin = self._i2c_bus.read_bytes(address, end - start)
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO/smbus.py", line 179, in read_bytes
    return self._device.read(number)
OSError: [Errno 121] Remote I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DAC.py", line 14, in <module>
    dac = adafruit_mcp4725.MCP4725(i2c)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_mcp4725.py", line 74, in __init__
    self._i2c = i2c_device.I2CDevice(i2c, address)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 68, in __init__
    self.__probe_for_device()
  File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 180, in __probe_for_device
    raise ValueError("No I2C device at address: %x" % self.device_address)
ValueError: No I2C device at address: 62

**Comment by ladyada** [comment]
probably a wiring issue, you can post to the forums of the vendor you bought your sensor from!

**Comment by hairem** [comment]
I did check my wiring and have been using this setup for months, but I needed to redo my pi installation and installed this library and just now started to get this error. I checked the MCP4725 on my arduino and it works fine there but I need it for my pi project. And if you look at the top I confirmed the module was reporting at address 0x62 like it should be, if my wiring was wrong I wouldn't of gotten that output. I am also using your example code to test the module.

**Comment by ladyada** [comment]
hi not sure what happened during your reinstall but an i/o error is usually a loose wire, bad ground etc. its likely hardware not software.

post to the forums of the vendor you bought your sensor from!

**Comment by hairem** [comment]
You know what, you were right and I was wrong, it looks like some gunk of some kind had made its way into my breadboard and was making for a poor connection, once cleaned it came back online. I am so sorry for bothering you. Please accept my apologizes.
