### ISSUE TITLE
OSError: [Errno 121] Remote I/O error on jetson nano

### ISSUE THREAD

**Issue by arunrajagopalan** [adafruit/Adafruit_CircuitPython_MCP4725#7]
I am using a jetson nano. The MCP4725 is visible on address 0x60. I get the following error when trying the adafruit example

~$ sudo python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> import busio
>>> import adafruit_mcp4725
>>> i2c = busio.I2C(board.SCL, board.SDA)
>>> dac = adafruit_mcp4725.MCP4725(i2c)
>>> dac.value = 32767
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/adafruit_mcp4725.py", line 131, in value
    self._write_fast_mode(raw_value)
  File "/usr/local/lib/python3.6/dist-packages/adafruit_mcp4725.py", line 90, in _write_fast_mode
    self._i2c.writeto(self._address, self._BUFFER, end=2)
  File "/home/vick/.local/lib/python3.6/site-packages/busio.py", line 64, in writeto
    return self._i2c.writeto(address, memoryview(buffer)[start:end], stop=stop)
  File "/home/vick/.local/lib/python3.6/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/home/vick/.local/lib/python3.6/site-packages/Adafruit_PureIO/smbus.py", line 244, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error

**Comment by ladyada** [comment]
@caternuson this is an ancient library, maybe needs updating to busdevice?

**Comment by caternuson** [comment]
It totally should even if that's not the issue.

@arunrajagopalan Do you have other I2C devices that you've gotten to work on your jetson nano?

**Comment by arunrajagopalan** [comment]
i haven’t tried other devices, but I have two of the MCP4725

**Comment by caternuson** [comment]
Post a photo of your setup showing all your wiring connections.

**Comment by BigTij** [comment]
i have the same problem... i tried the sht31d adafruit sensor with an arduino uno and it worked, but when i try reading it on a raspberry pi with their python code sample i get the same error: OSError: [Errno 121] Remote I/O error, and i did check if i could detect the i2c device by typing i2cdetect -y 1 and it shows up on address 0x44 just like i expected... i rly don't know what to do to solve this problem.

**Comment by ladyada** [comment]
@BigTij if you purchased the sensor from adafruit please post in the support forums - this is off-topic :)

**Comment by kattni** [comment]
Closing due to inactivity.
